name: 'Build and Test'
description: 'Build and test python library'
inputs:
 python-version:
  description: 'Python Version'
  required: true
  default: '3.8'

runs:
 using: "composite"
 steps:
  - name: Install dependencies
    run: |
     python -m pip install --upgrade pip
     python -m pip install flake8 pytest
     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    shell: bash

  - name: Lint with flake8
    run: |
     # stop the build if there are Python syntax errors or undefined names
     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    shell: bash

  - name: Test with pytest
    run: |
     pytest
    shell: bash
